# Generated by Django 3.1.4 on 2020-12-04 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=350, unique=True, verbose_name='Название поста')),
                ('anons', models.CharField(blank=True, max_length=500, verbose_name='Анонс поста')),
                ('text', models.TextField(blank=True, verbose_name='Текст поста')),
                ('image', models.ImageField(blank=True, upload_to='post_images\\img', verbose_name='Изображение поста')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Тэг поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 4, 17, 10, 10, 548876))),
                ('author', models.CharField(max_length=45, verbose_name='Имя комментатора')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
